### ISSUE TITLE
Abstract STIXViz visualization from backend

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/stix-viz#16]
I.e. the d3 graph library should be modularized so you can push it JSON and have it visualized.

**Comment by b-long** [comment]
It seems @YarThePirate has made progress in this regard, take a look at his project here : https://github.com/yarthepirate/stix2-viz/ .  There's a demo also available at https://yarthepirate.github.io/stix2-viz/ .

cc/ @CQRuu @gtback

**Comment by gtback** [comment]
Thanks, @b-long . The newest version is at https://github.com/oasis-open/cti-stix-visualization/ (demo at https://oasis-open.github.io/cti-stix-visualization/) .

This project (stix-viz) is for visualizing the older STIX 1.X XML content. To do so, it converted to a JSON format (which is different from STIX 2.0 JSON) and passed that to D3. 

I don't think we're ever going to actually do this though, so I'm going to close this issue.

**Comment by b-long** [comment]
Hi @gtback , thanks!  Sorry about my confusion, I appreciate you pointing that out 👍 I'll check out the latest 😃
