### ISSUE TITLE
Angular 6 Integration with Stixviz

### ISSUE THREAD

**Issue by mujtaba27** [STIXProject/stix-viz#20]
I Want to integrate stix visualization with angular 6. Is it possible. if yes can you help me with how to do it.

**Comment by clenk** [comment]
Hi, @mujtaba27. I'm sure it's possible, but I'm not an Angular expert and do not know what it would take.

Note that this tool is for STIX 1. If you want to work with STIX 2 data, there is a different visualization tool at https://github.com/oasis-open/cti-stix-visualization which may be easier to integrate with Angular.

**Comment by mujtaba27** [comment]
@clenk  Thankyou .
